# Generated by Django 4.1.4 on 2022-12-16 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.PositiveSmallIntegerField(choices=[('', 'Select'), (1, 'Male'), (2, 'Female'), (3, 'Other')], default=1)),
                ('date_of_birth', models.DateField()),
                ('occupation', models.CharField(max_length=100)),
                ('annual_income', models.PositiveBigIntegerField(verbose_name='RM')),
                ('address', models.TextField()),
                ('acc_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
