# Generated by Django 4.1.4 on 2023-01-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0003_alter_cashdonation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashdonation",
            name="invoice",
            field=models.ImageField(blank=True, null=True, upload_to="invoices/"),
        ),
    ]
