# Generated by Django 4.1.4 on 2023-01-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0004_cashdonation_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashdonation",
            name="invoice",
            field=models.FileField(blank=True, null=True, upload_to="invoices/"),
        ),
    ]
