# Generated by Django 4.1.4 on 2023-01-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0005_alter_cashdonation_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashdonation",
            name="status",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    ("", "Select"),
                    (1, "Rejected"),
                    (2, "Pending"),
                    (3, "Approved"),
                ],
                default=2,
            ),
        ),
    ]
