# Generated by Django 4.1.4 on 2023-01-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0006_alter_cashdonation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
