# Generated by Django 4.1.4 on 2022-12-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orphanage", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guardian", old_name="phone_number", new_name="phone",
        ),
    ]
