# Generated by Django 4.1.4 on 2022-12-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orphanage", "0003_alter_adoption_phone_alter_guardian_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orphan",
            name="dental_img",
            field=models.ImageField(blank=True, null=True, upload_to="x-rays/"),
        ),
    ]
