# Generated by Django 4.1.4 on 2022-12-28 22:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("orphanage", "0004_alter_orphan_dental_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outing",
            name="accompany_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=16, region=None, unique=True
            ),
        ),
    ]
