# Generated by Django 4.1.4 on 2022-12-28 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orphanage", "0005_alter_outing_accompany_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outing",
            name="date_out",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="outing",
            name="time_out",
            field=models.TimeField(default=datetime.time),
        ),
    ]
