# Generated by Django 4.1.4 on 2022-12-28 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orphanage", "0006_alter_outing_date_out_alter_outing_time_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outing",
            name="time_out",
            field=models.TimeField(default=datetime.time(7, 1, 43, 755721)),
        ),
    ]
