# Generated by Django 4.1.4 on 2022-12-29 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orphanage", "0008_alter_outing_status_alter_outing_time_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outing",
            name="status",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[("", "Select"), (1, "Outing"), (2, "Arrived")],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="outing",
            name="time_out",
            field=models.TimeField(default=datetime.time(8, 24, 37, 724672)),
        ),
    ]
